fixes issue #8 - checks for RYZOM_PATH env var, starts in build folder and turns on status line display in screen.

diff --git a/code/ryzom/tools/scripts/linux/shard b/code/ryzom/tools/scripts/linux/shard
--- a/code/ryzom/tools/scripts/linux/shard
+++ b/code/ryzom/tools/scripts/linux/shard
@@ -1,3 +1,8 @@
 #!/bin/sh
+if [ -z "${RYZOM_PATH+xxx}" ]; 
+then 
+	echo "ERROR: The variable RYZOM_PATH must be set! (e.g. /home/username/ryzom/code/ryzom)";
+	exit 1;
+fi
 cd $RYZOM_PATH/server
 /bin/sh $RYZOM_PATH/tools/scripts/linux/ryzom_domain_screen_wrapper.sh $*
